// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_e8gMmj8GLjppp-or58kX5o-Gov9luwU',
    appId: '1:1052436756737:android:0c734cd81a54dd3725c300',
    messagingSenderId: '1052436756737',
    projectId: 'mobx-reminders-course',
    storageBucket: 'mobx-reminders-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3glz478gmkZU-SOupFZo1CmITmJv0M9o',
    appId: '1:1052436756737:ios:597e04aa63b5e3ef25c300',
    messagingSenderId: '1052436756737',
    projectId: 'mobx-reminders-course',
    storageBucket: 'mobx-reminders-course.appspot.com',
    iosClientId: '1052436756737-70ra1d2otkdo3jndqhn2ardgpvgb66aa.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mobxreminders-course',
  );
}
